<?php

namespace CruiseBundle\Repository;

/**
 * OrderItemServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
