<?php

namespace CruiseBundle\Repository;

/**
 * ProgramItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramItemRepository extends \Doctrine\ORM\EntityRepository
{
}
