<?php

namespace CruiseBundle\Repository;

/**
 * RoomDiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomDiscountRepository extends \Doctrine\ORM\EntityRepository
{
}
