<?php

namespace CruiseBundle\Repository;

/**
 * ShipCabinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipCabinRepository extends \Doctrine\ORM\EntityRepository
{
}
