<?php

namespace CruiseBundle\Repository;

/**
 * ShipCabinTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipCabinTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
