<?php

namespace CruiseBundle\Repository;

/**
 * ShipRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
