<?php

namespace CruiseBundle\Repository;

/**
 * ShipCabinPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipCabinPlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
