<?php

namespace CruiseBundle\Repository;

/**
 * ShipDeckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipDeckRepository extends \Doctrine\ORM\EntityRepository
{
}
