<?php

namespace CruiseBundle\Repository;

/**
 * TurOperatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurOperatorRepository extends \Doctrine\ORM\EntityRepository
{
}
