<?php

namespace CruiseBundle\Repository;

/**
 * TypeDiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDiscountRepository extends \Doctrine\ORM\EntityRepository
{
}
