<?php

namespace CruiseBundle\Repository;

/**
 * TypeDocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDocRepository extends \Doctrine\ORM\EntityRepository
{
}
