<?php

namespace CruiseBundle\Repository;

/**
 * TypePlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
